"use client";

import { useEffect, useState } from "react";

type ProposedFile = {
  path: string;
  content: string;
};

type StoredSuggestion = {
  sourcePrNumber: number;
  sourcePrUrl: string;
  sourcePrTitle: string;
  summary: string;
  files: ProposedFile[];
  navConfigContent: string | null;
  generatedAt: string;
};

type LoadState =
  | { status: "loading" }
  | { status: "error" }
  | { status: "loaded"; suggestions: StoredSuggestion[] };

export default function ObservabilityPage() {
  const [state, setState] = useState<LoadState>({ status: "loading" });

  useEffect(() => {
    let cancelled = false;

    fetch("/api/doc-suggestions")
      .then((res) => {
        if (!res.ok) throw new Error(`request failed with status ${res.status}`);
        return res.json();
      })
      .then((data: { suggestions: StoredSuggestion[] }) => {
        if (!cancelled) setState({ status: "loaded", suggestions: data.suggestions });
      })
      .catch(() => {
        if (!cancelled) setState({ status: "error" });
      });

    return () => {
      cancelled = true;
    };
  }, []);

  return (
    <div>
      <h1 className="text-2xl font-semibold text-slate-900 dark:text-white">
        Observability
      </h1>
      <p className="mt-2 text-slate-600 dark:text-slate-300">
        Doc-update suggestions generated by the automation in{" "}
        <code className="rounded bg-slate-900/5 px-1 py-0.5 text-sm dark:bg-white/10">
          api/github-webhook.ts
        </code>{" "}
        whenever a merged PR touches watched docs.
      </p>

      <div className="mt-6">
        {state.status === "loading" && (
          <p className="text-sm text-slate-500 dark:text-slate-400">Loading…</p>
        )}

        {state.status === "error" && (
          <p className="text-sm text-red-600 dark:text-red-400">
            Couldn&apos;t load doc-update suggestions. Try refreshing the page.
          </p>
        )}

        {state.status === "loaded" && state.suggestions.length === 0 && (
          <p className="text-sm text-slate-500 dark:text-slate-400">
            No doc-update suggestions yet.
          </p>
        )}

        {state.status === "loaded" && state.suggestions.length > 0 && (
          <ul className="space-y-4">
            {state.suggestions.map((suggestion) => (
              <li
                key={suggestion.sourcePrNumber}
                className="rounded-xl border border-slate-900/10 p-4 dark:border-white/10"
              >
                <div className="flex items-baseline justify-between gap-4">
                  <a
                    href={suggestion.sourcePrUrl}
                    className="font-medium text-slate-900 hover:underline dark:text-white"
                  >
                    #{suggestion.sourcePrNumber} {suggestion.sourcePrTitle}
                  </a>
                  <time
                    dateTime={suggestion.generatedAt}
                    className="shrink-0 text-xs text-slate-500 dark:text-slate-400"
                  >
                    {new Date(suggestion.generatedAt).toLocaleString()}
                  </time>
                </div>
                <p className="mt-2 text-sm text-slate-600 dark:text-slate-300">
                  {suggestion.summary}
                </p>
                {suggestion.files.length > 0 && (
                  <ul className="mt-3 flex flex-wrap gap-2">
                    {suggestion.files.map((file) => (
                      <li
                        key={file.path}
                        className="rounded-md bg-slate-900/5 px-2 py-1 font-mono text-xs text-slate-600 dark:bg-white/10 dark:text-slate-300"
                      >
                        {file.path}
                      </li>
                    ))}
                  </ul>
                )}
              </li>
            ))}
          </ul>
        )}
      </div>
    </div>
  );
}
