"use client";

import { useEffect, useState } from "react";

type ProposedFile = {
  path: string;
  content: string;
};

type SuggestionStatus = "pending" | "accepted" | "dismissed";

type StoredSuggestion = {
  sourcePrNumber: number;
  sourcePrUrl: string;
  sourcePrTitle: string;
  summary: string;
  files: ProposedFile[];
  navConfigContent: string | null;
  generatedAt: string;
  status: SuggestionStatus;
};

const STATUS_BADGE_STYLES: Record<SuggestionStatus, string> = {
  pending: "bg-amber-100 text-amber-800 dark:bg-amber-400/10 dark:text-amber-400",
  accepted: "bg-emerald-100 text-emerald-800 dark:bg-emerald-400/10 dark:text-emerald-400",
  dismissed: "bg-slate-100 text-slate-600 dark:bg-white/10 dark:text-slate-400",
};

const STATUS_LABELS: Record<SuggestionStatus, string> = {
  pending: "Pending",
  accepted: "Accepted",
  dismissed: "Dismissed",
};

type LoadState =
  | { status: "loading" }
  | { status: "error" }
  | { status: "loaded"; suggestions: StoredSuggestion[] };

export default function ObservabilityPage() {
  const [state, setState] = useState<LoadState>({ status: "loading" });

  useEffect(() => {
    let cancelled = false;

    fetch("/api/doc-suggestions")
      .then((res) => {
        if (!res.ok) throw new Error(`request failed with status ${res.status}`);
        return res.json();
      })
      .then((data: { suggestions: StoredSuggestion[] }) => {
        if (!cancelled) setState({ status: "loaded", suggestions: data.suggestions });
      })
      .catch(() => {
        if (!cancelled) setState({ status: "error" });
      });

    return () => {
      cancelled = true;
    };
  }, []);

  function getDashboardSecret(): string | null {
    let secret = sessionStorage.getItem("dashboardApiSecret");
    if (!secret) {
      secret = window.prompt("Enter the dashboard API secret to accept/dismiss suggestions:");
      if (secret) sessionStorage.setItem("dashboardApiSecret", secret);
    }
    return secret;
  }

  function updateStatus(prNumber: number, status: SuggestionStatus) {
    if (state.status !== "loaded") return;
    const previousSuggestions = state.suggestions;

    const secret = getDashboardSecret();
    if (!secret) return;

    setState({
      status: "loaded",
      suggestions: previousSuggestions.map((s) =>
        s.sourcePrNumber === prNumber ? { ...s, status } : s,
      ),
    });

    fetch("/api/doc-suggestion-status", {
      method: "PATCH",
      headers: {
        "Content-Type": "application/json",
        Authorization: `Bearer ${secret}`,
      },
      body: JSON.stringify({ prNumber, status }),
    }).then((res) => {
      if (!res.ok) {
        if (res.status === 401) sessionStorage.removeItem("dashboardApiSecret");
        throw new Error(`request failed with status ${res.status}`);
      }
    }).catch(() => {
      setState({ status: "loaded", suggestions: previousSuggestions });
    });
  }

  return (
    <div>
      <h1 className="text-2xl font-semibold text-slate-900 dark:text-white">
        Observability
      </h1>
      <p className="mt-2 text-slate-600 dark:text-slate-300">
        Doc-update suggestions generated by the automation in{" "}
        <code className="rounded bg-slate-900/5 px-1 py-0.5 text-sm dark:bg-white/10">
          api/github-webhook.ts
        </code>{" "}
        whenever a merged PR touches watched docs.
      </p>

      <div className="mt-6">
        {state.status === "loading" && (
          <p className="text-sm text-slate-500 dark:text-slate-400">Loading…</p>
        )}

        {state.status === "error" && (
          <p className="text-sm text-red-600 dark:text-red-400">
            Couldn&apos;t load doc-update suggestions. Try refreshing the page.
          </p>
        )}

        {state.status === "loaded" && state.suggestions.length === 0 && (
          <p className="text-sm text-slate-500 dark:text-slate-400">
            No doc-update suggestions yet.
          </p>
        )}

        {state.status === "loaded" && state.suggestions.length > 0 && (
          <ul className="space-y-4">
            {state.suggestions.map((suggestion) => (
              <li
                key={suggestion.sourcePrNumber}
                className="rounded-xl border border-slate-900/10 p-4 dark:border-white/10"
              >
                <div className="flex items-baseline justify-between gap-4">
                  <a
                    href={suggestion.sourcePrUrl}
                    className="font-medium text-slate-900 hover:underline dark:text-white"
                  >
                    #{suggestion.sourcePrNumber} {suggestion.sourcePrTitle}
                  </a>
                  <div className="flex shrink-0 items-center gap-2">
                    <span
                      className={`rounded-full px-2 py-0.5 text-xs font-medium ${STATUS_BADGE_STYLES[suggestion.status]}`}
                    >
                      {STATUS_LABELS[suggestion.status]}
                    </span>
                    <time
                      dateTime={suggestion.generatedAt}
                      className="text-xs text-slate-500 dark:text-slate-400"
                    >
                      {new Date(suggestion.generatedAt).toLocaleString()}
                    </time>
                  </div>
                </div>
                <p className="mt-2 text-sm text-slate-600 dark:text-slate-300">
                  {suggestion.summary}
                </p>
                {suggestion.files.length > 0 && (
                  <ul className="mt-3 flex flex-wrap gap-2">
                    {suggestion.files.map((file) => (
                      <li
                        key={file.path}
                        className="rounded-md bg-slate-900/5 px-2 py-1 font-mono text-xs text-slate-600 dark:bg-white/10 dark:text-slate-300"
                      >
                        {file.path}
                      </li>
                    ))}
                  </ul>
                )}
                {suggestion.status === "pending" && (
                  <div className="mt-3 flex gap-2">
                    <button
                      type="button"
                      onClick={() => updateStatus(suggestion.sourcePrNumber, "accepted")}
                      className="rounded-md bg-emerald-600 px-2.5 py-1 text-xs font-medium text-white hover:bg-emerald-500"
                    >
                      Accept
                    </button>
                    <button
                      type="button"
                      onClick={() => updateStatus(suggestion.sourcePrNumber, "dismissed")}
                      className="rounded-md bg-slate-900/5 px-2.5 py-1 text-xs font-medium text-slate-700 hover:bg-slate-900/10 dark:bg-white/10 dark:text-slate-200 dark:hover:bg-white/20"
                    >
                      Dismiss
                    </button>
                  </div>
                )}
              </li>
            ))}
          </ul>
        )}
      </div>
    </div>
  );
}
